// Use this and update
//https://developer.nrel.gov/api/alt-fuel-stations/v1.json?api_key=DEMO_KEY&fuel_type=ELEC,BD,HY&limit=all

export default function rawDataSmall()  {
  return {
    "station_locator_url": "https://afdc.energy.gov/stations/",
    "total_results": 57785,
    "station_counts": {
      "total": 149526,
      "fuels": {
        "BD": {
          "total": 1197
        },
        "E85": {
          "total": 0
        },
        "ELEC": {
          "total": 148187,
          "stations": {
            "total": 56446
          }
        },
        "HY": {
          "total": 142
        },
        "LNG": {
          "total": 0
        },
        "CNG": {
          "total": 0
        },
        "LPG": {
          "total": 0
        }
      }
    },
    "fuel_stations": [
      {
        "access_code": "private",
        "access_days_time": "Fleet use only",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2021-07-14",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Private",
        "id": 1517,
        "open_date": "1999-10-15",
        "owner_type_code": "LG",
        "status_code": "E",
        "restricted_access": null,
        "station_name": "LADWP - Truesdale Center",
        "station_phone": null,
        "updated_at": "2022-07-18T11:36:50Z",
        "facility_type": "UTILITY",
        "geocode_status": "GPS",
        "latitude": 34.2483191527193,
        "longitude": -118.3879713743439,
        "city": "Sun Valley",
        "intersection_directions": null,
        "plus4": null,
        "state": "CA",
        "street_address": "11797 Truesdale St",
        "zip": "91352",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "CHADEMO",
          "J1772",
          "J1772COMBO"
        ],
        "ev_dc_fast_num": 3,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 39,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": null,
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Privé",
        "ev_pricing_fr": null
      },
      {
        "access_code": "private",
        "access_days_time": null,
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2021-07-14",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Private",
        "id": 1519,
        "open_date": "2020-02-28",
        "owner_type_code": "LG",
        "status_code": "E",
        "restricted_access": null,
        "station_name": "LADWP - West LA District Office",
        "station_phone": null,
        "updated_at": "2022-07-18T11:36:50Z",
        "facility_type": "UTILITY",
        "geocode_status": "200-8",
        "latitude": 34.052542,
        "longitude": -118.448504,
        "city": "Los Angeles",
        "intersection_directions": null,
        "plus4": null,
        "state": "CA",
        "street_address": "1394 S Sepulveda Blvd",
        "zip": "90024",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "J1772"
        ],
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 4,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": "Free",
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Privé",
        "ev_pricing_fr": null
      },
      {
        "access_code": "public",
        "access_days_time": "24 hours daily; pay lot",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2020-11-09",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Public",
        "id": 1523,
        "open_date": "1995-08-30",
        "owner_type_code": "P",
        "status_code": "E",
        "restricted_access": false,
        "station_name": "Los Angeles Convention Center",
        "station_phone": "213-741-1151",
        "updated_at": "2021-03-11T23:22:17Z",
        "facility_type": "PARKING_GARAGE",
        "geocode_status": "GPS",
        "latitude": 34.040539,
        "longitude": -118.271387,
        "city": "Los Angeles",
        "intersection_directions": "West hall and South hall",
        "plus4": null,
        "state": "CA",
        "street_address": "1201 S Figueroa St",
        "zip": "90015",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "J1772"
        ],
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 12,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": null,
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Public",
        "ev_pricing_fr": null
      },
      {
        "access_code": "private",
        "access_days_time": "For fleet and employee use only",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2021-07-14",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Private",
        "id": 1525,
        "open_date": "1999-10-15",
        "owner_type_code": "LG",
        "status_code": "E",
        "restricted_access": null,
        "station_name": "LADWP - John Ferraro Building",
        "station_phone": null,
        "updated_at": "2022-07-18T11:36:50Z",
        "facility_type": "UTILITY",
        "geocode_status": "GPS",
        "latitude": 34.059133,
        "longitude": -118.248589,
        "city": "Los Angeles",
        "intersection_directions": "Across Hope",
        "plus4": null,
        "state": "CA",
        "street_address": "111 N Hope St",
        "zip": "90012",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "CHADEMO",
          "J1772",
          "J1772COMBO"
        ],
        "ev_dc_fast_num": 2,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 311,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": null,
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Privé",
        "ev_pricing_fr": null
      },
      {
        "access_code": "private",
        "access_days_time": "Fleet use only",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2021-07-14",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Private",
        "id": 1531,
        "open_date": "2018-05-01",
        "owner_type_code": "LG",
        "status_code": "E",
        "restricted_access": null,
        "station_name": "LADWP - Haynes Power Plant",
        "station_phone": null,
        "updated_at": "2022-07-18T11:36:50Z",
        "facility_type": "UTILITY",
        "geocode_status": "GPS",
        "latitude": 33.759802,
        "longitude": -118.096665,
        "city": "Long Beach",
        "intersection_directions": null,
        "plus4": null,
        "state": "CA",
        "street_address": "6801 E 2nd St",
        "zip": "90803",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "CHADEMO",
          "J1772",
          "J1772COMBO"
        ],
        "ev_dc_fast_num": 1,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 19,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": null,
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Privé",
        "ev_pricing_fr": null
      },
      {
        "access_code": "private",
        "access_days_time": "Fleet use only",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2021-07-14",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Private",
        "id": 1552,
        "open_date": "1999-10-15",
        "owner_type_code": "LG",
        "status_code": "E",
        "restricted_access": null,
        "station_name": "LADWP - Harbor Generating Station",
        "station_phone": null,
        "updated_at": "2022-07-18T11:36:50Z",
        "facility_type": "UTILITY",
        "geocode_status": "200-8",
        "latitude": 33.770508,
        "longitude": -118.265628,
        "city": "Wilmington",
        "intersection_directions": "At B St",
        "plus4": null,
        "state": "CA",
        "street_address": "161 N Island Ave",
        "zip": "90744",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "J1772"
        ],
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 10,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": null,
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Privé",
        "ev_pricing_fr": null
      },
      {
        "access_code": "private",
        "access_days_time": "Fleet use only",
        "access_detail_code": "GOVERNMENT",
        "cards_accepted": null,
        "date_last_confirmed": "2021-07-14",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Private - Government only",
        "id": 1556,
        "open_date": "2016-01-01",
        "owner_type_code": "LG",
        "status_code": "E",
        "restricted_access": null,
        "station_name": "LADWP - Sylmar West",
        "station_phone": null,
        "updated_at": "2022-07-18T11:36:50Z",
        "facility_type": "UTILITY",
        "geocode_status": "200-8",
        "latitude": 34.30309,
        "longitude": -118.480505,
        "city": "Sylmar",
        "intersection_directions": null,
        "plus4": null,
        "state": "CA",
        "street_address": "13201 Sepulveda Blvd",
        "zip": "91342",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "J1772"
        ],
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 2,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": null,
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Privé - Réservé au gouvernement",
        "ev_pricing_fr": null
      },
      {
        "access_code": "private",
        "access_days_time": "Fleet and employee use only",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2021-07-14",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Private",
        "id": 1572,
        "open_date": "1999-10-15",
        "owner_type_code": "LG",
        "status_code": "E",
        "restricted_access": null,
        "station_name": "LADWP - EV Service Center",
        "station_phone": null,
        "updated_at": "2022-07-18T11:36:50Z",
        "facility_type": "UTILITY",
        "geocode_status": "200-8",
        "latitude": 34.066801,
        "longitude": -118.227605,
        "city": "Los Angeles",
        "intersection_directions": null,
        "plus4": null,
        "state": "CA",
        "street_address": "1630 N Main St",
        "zip": "90012",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "CHADEMO",
          "J1772"
        ],
        "ev_dc_fast_num": 1,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 46,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": null,
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Privé",
        "ev_pricing_fr": null
      },
      {
        "access_code": "private",
        "access_days_time": "Fleet use only",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2021-07-14",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Private",
        "id": 1573,
        "open_date": "2019-04-01",
        "owner_type_code": "LG",
        "status_code": "E",
        "restricted_access": null,
        "station_name": "LADWP - Fairfax Center",
        "station_phone": null,
        "updated_at": "2022-07-18T11:36:50Z",
        "facility_type": "UTILITY",
        "geocode_status": "200-8",
        "latitude": 34.036777,
        "longitude": -118.368841,
        "city": "Los Angeles",
        "intersection_directions": null,
        "plus4": null,
        "state": "CA",
        "street_address": "2311 S Fairfax Ave",
        "zip": "90016",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "J1772"
        ],
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 13,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": null,
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Privé",
        "ev_pricing_fr": null
      },
      {
        "access_code": "public",
        "access_days_time": "24 hours daily",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2022-09-14",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Public",
        "id": 1583,
        "open_date": "1996-10-15",
        "owner_type_code": "SG",
        "status_code": "E",
        "restricted_access": false,
        "station_name": "California Air Resources Board",
        "station_phone": "626-575-6800",
        "updated_at": "2022-09-14T15:49:44Z",
        "facility_type": "STATE_GOV",
        "geocode_status": "GPS",
        "latitude": 34.06872,
        "longitude": -118.064,
        "city": "El Monte",
        "intersection_directions": null,
        "plus4": null,
        "state": "CA",
        "street_address": "9530 Telstar Ave",
        "zip": "91731",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "J1772"
        ],
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 3,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": "Free",
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Public",
        "ev_pricing_fr": null
      },
      {
        "access_code": "private",
        "access_days_time": "Fleet use only",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2021-07-14",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Private",
        "id": 1589,
        "open_date": "1999-10-15",
        "owner_type_code": "LG",
        "status_code": "E",
        "restricted_access": null,
        "station_name": "LADWP - Palmetto Center",
        "station_phone": null,
        "updated_at": "2022-07-18T11:36:50Z",
        "facility_type": "UTILITY",
        "geocode_status": "GPS",
        "latitude": 34.039736,
        "longitude": -118.236065,
        "city": "Los Angeles",
        "intersection_directions": null,
        "plus4": null,
        "state": "CA",
        "street_address": "1212 Palmetto St",
        "zip": "90013",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "J1772"
        ],
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 10,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": null,
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Privé",
        "ev_pricing_fr": null
      },
      {
        "access_code": "public",
        "access_days_time": "24 hours daily",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2021-07-14",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Public",
        "id": 6355,
        "open_date": "1997-07-30",
        "owner_type_code": "P",
        "status_code": "E",
        "restricted_access": false,
        "station_name": "Scripps Green Hospital",
        "station_phone": null,
        "updated_at": "2022-02-10T19:42:29Z",
        "facility_type": "HOSPITAL",
        "geocode_status": "GPS",
        "latitude": 32.89947,
        "longitude": -117.243,
        "city": "La Jolla",
        "intersection_directions": "Patient Parking Structure, level G",
        "plus4": null,
        "state": "CA",
        "street_address": "10666 N Torrey Pines Rd",
        "zip": "92037",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "J1772"
        ],
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 1,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": "Pay to Park",
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Public",
        "ev_pricing_fr": null
      },
      {
        "access_code": "public",
        "access_days_time": "Dealership business hours",
        "access_detail_code": "CALL",
        "cards_accepted": null,
        "date_last_confirmed": "2021-12-09",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Public - Call ahead",
        "id": 6405,
        "open_date": "2012-12-11",
        "owner_type_code": "P",
        "status_code": "E",
        "restricted_access": false,
        "station_name": "Galpin Motors",
        "station_phone": "800-256-6219",
        "updated_at": "2022-02-10T19:42:29Z",
        "facility_type": "CAR_DEALER",
        "geocode_status": "200-9",
        "latitude": 34.221665,
        "longitude": -118.468371,
        "city": "Sepulveda",
        "intersection_directions": null,
        "plus4": null,
        "state": "CA",
        "street_address": "15421 Roscoe Blvd",
        "zip": "91343",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "J1772"
        ],
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 2,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": "Free",
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Public - Appeler à l'avance",
        "ev_pricing_fr": null
      },
      {
        "access_code": "public",
        "access_days_time": "6am-12am daily",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2020-02-06",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Public",
        "id": 6425,
        "open_date": "1997-08-30",
        "owner_type_code": "P",
        "status_code": "E",
        "restricted_access": false,
        "station_name": "Galleria at Tyler",
        "station_phone": "951-351-3110",
        "updated_at": "2021-03-11T23:22:17Z",
        "facility_type": "SHOPPING_MALL",
        "geocode_status": "GPS",
        "latitude": 33.909914,
        "longitude": -117.459053,
        "city": "Riverside",
        "intersection_directions": null,
        "plus4": null,
        "state": "CA",
        "street_address": "1299 Galleria at Tyler",
        "zip": "92503",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "J1772"
        ],
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 4,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": "Free",
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Public",
        "ev_pricing_fr": null
      },
      {
        "access_code": "public",
        "access_days_time": "24 hours daily; pay lot",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2022-01-10",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Public",
        "id": 6505,
        "open_date": "1997-08-30",
        "owner_type_code": "LG",
        "status_code": "E",
        "restricted_access": false,
        "station_name": "City of Pasadena - Holly Street Garage",
        "station_phone": "626-744-7665",
        "updated_at": "2022-02-10T19:42:29Z",
        "facility_type": "PARKING_GARAGE",
        "geocode_status": "200-8",
        "latitude": 34.14762,
        "longitude": -118.147111,
        "city": "Pasadena",
        "intersection_directions": null,
        "plus4": null,
        "state": "CA",
        "street_address": "150 E Holly St",
        "zip": "91103",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "J1772"
        ],
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 16,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": "Free",
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Public",
        "ev_pricing_fr": null
      },
      {
        "access_code": "public",
        "access_days_time": "24 hours daily; pay lot",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2020-12-03",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Public",
        "id": 6506,
        "open_date": "1997-08-30",
        "owner_type_code": "LG",
        "status_code": "E",
        "restricted_access": false,
        "station_name": "City of Pasadena - De Lacey Garage",
        "station_phone": "626-744-7665",
        "updated_at": "2021-03-11T23:22:17Z",
        "facility_type": "PARKING_GARAGE",
        "geocode_status": "GPS",
        "latitude": 34.145138,
        "longitude": -118.152655,
        "city": "Pasadena",
        "intersection_directions": null,
        "plus4": null,
        "state": "CA",
        "street_address": "45 De Lacey Ave",
        "zip": "91105",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "J1772"
        ],
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 2,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": "Free",
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Public",
        "ev_pricing_fr": null
      },
      {
        "access_code": "public",
        "access_days_time": "24 hours daily; pay lot",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2020-12-03",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Public",
        "id": 6507,
        "open_date": "1997-08-30",
        "owner_type_code": "LG",
        "status_code": "E",
        "restricted_access": false,
        "station_name": "City of Pasadena - Schoolhouse Garage",
        "station_phone": "626-744-7665",
        "updated_at": "2021-03-11T23:22:17Z",
        "facility_type": "PARKING_GARAGE",
        "geocode_status": "200-8",
        "latitude": 34.145119,
        "longitude": -118.150133,
        "city": "Pasadena",
        "intersection_directions": null,
        "plus4": null,
        "state": "CA",
        "street_address": "33 E Green St",
        "zip": "91105",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "J1772"
        ],
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 3,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": "Free",
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Public",
        "ev_pricing_fr": null
      },
      {
        "access_code": "public",
        "access_days_time": "24 hours daily",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2021-07-14",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Public",
        "id": 6509,
        "open_date": "1997-08-31",
        "owner_type_code": "P",
        "status_code": "E",
        "restricted_access": false,
        "station_name": "Bristol Farms",
        "station_phone": "626-441-5450",
        "updated_at": "2022-02-10T19:42:29Z",
        "facility_type": "GROCERY",
        "geocode_status": "200-9",
        "latitude": 34.118433,
        "longitude": -118.149597,
        "city": "South Pasadena",
        "intersection_directions": null,
        "plus4": null,
        "state": "CA",
        "street_address": "606 Fair Oaks Ave",
        "zip": "91030",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": null,
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": null,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": "1 LP Inductive",
        "ev_pricing": null,
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Public",
        "ev_pricing_fr": null
      },
      {
        "access_code": "public",
        "access_days_time": "24 hours daily; pay lot; see valet for access",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2021-01-14",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Public",
        "id": 7172,
        "open_date": "2012-05-04",
        "owner_type_code": "P",
        "status_code": "E",
        "restricted_access": false,
        "station_name": "Hyatt Regency Long Beach",
        "station_phone": "562-491-1234",
        "updated_at": "2021-03-11T23:22:17Z",
        "facility_type": "HOTEL",
        "geocode_status": "GPS",
        "latitude": 33.7637,
        "longitude": -118.192,
        "city": "Long Beach",
        "intersection_directions": null,
        "plus4": null,
        "state": "CA",
        "street_address": "200 S Pine Ave",
        "zip": "90802",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "J1772"
        ],
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 1,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": "Free",
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Public",
        "ev_pricing_fr": null
      },
      {
        "access_code": "public",
        "access_days_time": "24 hours daily; pay lot",
        "access_detail_code": null,
        "cards_accepted": null,
        "date_last_confirmed": "2022-08-10",
        "expected_date": null,
        "fuel_type_code": "ELEC",
        "groups_with_access_code": "Public",
        "id": 7184,
        "open_date": "1998-06-30",
        "owner_type_code": "LG",
        "status_code": "E",
        "restricted_access": false,
        "station_name": "Los Angeles International Airport (LAX) - Lot 6",
        "station_phone": "310-646-2911",
        "updated_at": "2022-08-10T13:32:10Z",
        "facility_type": "AIRPORT",
        "geocode_status": "GPS",
        "latitude": 33.94325,
        "longitude": -118.403342,
        "city": "Los Angeles",
        "intersection_directions": "Central Terminal Area (CTA) - P6",
        "plus4": null,
        "state": "CA",
        "street_address": "1 World Way",
        "zip": "90045",
        "country": "US",
        "bd_blends": null,
        "cng_dispenser_num": null,
        "cng_fill_type_code": null,
        "cng_psi": null,
        "cng_renewable_source": null,
        "cng_total_compression": null,
        "cng_total_storage": null,
        "cng_vehicle_class": null,
        "e85_blender_pump": null,
        "e85_other_ethanol_blends": null,
        "ev_connector_types": [
          "J1772"
        ],
        "ev_dc_fast_num": null,
        "ev_level1_evse_num": null,
        "ev_level2_evse_num": 20,
        "ev_network": "Non-Networked",
        "ev_network_web": null,
        "ev_other_evse": null,
        "ev_pricing": "$2 service fee + $0.45 per kWh",
        "ev_renewable_source": null,
        "hy_is_retail": null,
        "hy_pressures": null,
        "hy_standards": null,
        "hy_status_link": null,
        "lng_renewable_source": null,
        "lng_vehicle_class": null,
        "lpg_primary": null,
        "lpg_nozzle_types": null,
        "ng_fill_type_code": null,
        "ng_psi": null,
        "ng_vehicle_class": null,
        "access_days_time_fr": null,
        "intersection_directions_fr": null,
        "bd_blends_fr": null,
        "groups_with_access_code_fr": "Public",
        "ev_pricing_fr": null
      }
    ]
  }
}
